### ISSUE TITLE
Column already exists 'id' on join contraint

### ISSUE THREAD

**Issue by surgiie** [teamtnt/laravel-scout-tntsearch-driver#202]
So i have this users table that has a `manager_id`. Im doing a join on the table so i can allow the results to be sorted by the managers name.Maybe my logic is wrong or im missing something, but when i do the join and order, i get the results im expecting, but when do the join and then try to do a search on that using contraints i get an exception:

```php

Column already exists: 1060 Duplicate column name 'id' (SQL: select `users`.`id` from `users` left join (select * from `users` inner join `users` as `mg` on `mg`.`manager_id` = `users`.`id` and `mg`.`id` != 2 where `users`.`id` in (20, 221, 155, 319, 333, 33, 255) order by `users`.`name` desc) as sub on `sub`.`id` = `users`.`id` where `users`.`id` in (20, 221, 155, 319, 333, 33, 255) and `sub`.`id` is null and `users`.`deleted_at` is null)

```

```php
$builder->join('users as mg', function ($join) {
    $join->on('mg.manager_id', '=', 'users.id')->where('mg.id', '!=', auth()->id());
})->orderBy('users.name', $direction);

//$builder returns expected result


//exception thrown here
User::search($q)->constrain($builder);
```

relevant stack trace:

```
[2018-10-02 17:15:36] local.ERROR: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' (SQL: select `users`.`id` from `users` left join (select * from `users` inner join `users` as `mg` on `mg`.`manager_id` = `users`.`id` and `mg`.`id` != 2 where `users`.`id` in (20, 221, 155, 319, 333, 33, 255) order by `users`.`name` desc) as sub on `sub`.`id` = `users`.`id` where `users`.`id` in (20, 221, 155, 319, 333, 33, 255) and `sub`.`id` is null and `users`.`deleted_at` is null) {"userId":2,"email":"scompean@dialinginnovations.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' (SQL: select `users`.`id` from `users` left join (select * from `users` inner join `users` as `mg` on `mg`.`manager_id` = `users`.`id` and `mg`.`id` != 2 where `users`.`id` in (20, 221, 155, 319, 333, 33, 255) order by `users`.`name` desc) as sub on `sub`.`id` = `users`.`id` where `users`.`id` in (20, 221, 155, 319, 333, 33, 255) and `sub`.`id` is null and `users`.`deleted_at` is null) at /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' at /home/surgiie/Desktop/projects/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82, PDOException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' at /home/surgiie/Desktop/projects/CRM/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80)
[stacktrace]
#0 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `users`....', Array, Object(Closure))
#1 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `users`....', Array, Object(Closure))
#2 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2027): Illuminate\\Database\\Connection->select('select `users`....', Array, true)
#3 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2219): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2499): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2221): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/surgiie/Desktop/projects/CRM/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(712): Illuminate\\Database\\Query\\Builder->pluck('id', NULL)
#7 /home/surgiie/Desktop/projects/CRM/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(297): Illuminate\\Database\\Eloquent\\Builder->pluck('id')
#8 /home/surgiie/Desktop/projects/CRM/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(117): TeamTNT\\Scout\\Engines\\TNTSearchEngine->discardIdsFromResultSetByConstraints(Object(Laravel\\Scout\\Builder), Array)
#9 /home/surgiie/Desktop/projects/CRM/vendor/laravel/scout/src/Builder.php(271): TeamTNT\\Scout\\Engines\\TNTSearchEngine->paginate(Object(Laravel\\Scout\\Builder), 10, 1)


```

I can do a search no problem when i dont do the join/sort. Am i missing something?

**Comment by surgiie** [comment]
Nevermind. I see that orderBys need to go after the search per the readme.

**Comment by rico** [comment]
@surgiie can you post how you got it working in the end? I'm having the same problem, but the `orderBy` is after the search. Thanks!

**Comment by MateusFGoncalves** [comment]
Hey guys, i resolved this problem.  In my case I was making a join and I had both the user ID in one table and the other, which defined this binding between both tables, so what I did was select only the columns I really needed, eliminating which was duplicated just as the message says, so I solved the problem, so was my solution:

```
             $queryBuilder = DB::table('tab_pontuacoes_secretarias')
                ->whereNull('tab_pontuacoes_secretarias.deleted_at')
                ->leftJoin('tab_secretarias', function($query)
                {
                    $query->on('tab_pontuacoes_secretarias.secretaria_id', '=', 'tab_secretarias.id'); 
                })                                     
                ->select(
                    'tab_secretarias.nome',                         
                    'tab_secretarias.med_id',
                    'tab_secretarias.id',                        
                    'tab_pontuacoes_secretarias.id',
                    'tab_pontuacoes_secretarias.descricao',
                    'tab_pontuacoes_secretarias.data',
                    'tab_pontuacoes_secretarias.pontos',
                    'tab_pontuacoes_secretarias.deleted_at',
                    tab_pontuacoes_secretarias.'secretaria_id'                    
                )
                ->orderBy('data', 'desc');
```

Use the select option to select the columns you need ...
